#!/usr/bin/make -f
# Makefile for WineASIO #
# --------------------- #
# Created by falkTX
# Initially generated by winemaker
#

ifeq ($(ARCH),)
$(error incorrect use of Makefile, ARCH var is missing)
endif
ifeq ($(M),)
$(error incorrect use of Makefile, M var is missing)
endif

pwasio_dll_MODULE = pwasio$(M).dll

PREFIX = /usr
DLLS = $(pwasio_dll_MODULE) $(pwasio_dll_MODULE).so

### Tools

CC        = gcc
WINEBUILD = winebuild
WINECC    = winegcc

### Common settings

ifeq ($(DEBUG),true)
CEXTRA               += -O0 -DDEBUG -g -D__WINESRC__
else
CEXTRA               += -O2 -DNDEBUG -fvisibility=hidden
endif


VERSION_MAJOR := 0
VERSION_MINOR := 1
VERSION_PATCH := 0

CEXTRA = $(CFLAGS) -m$(M) -D_REENTRANT -fPIC -Wall -pipe
CEXTRA += -Wextra -Wno-missing-field-initializers 
CEXTRA += $(shell $(PKG_CONFIG) --cflags libpipewire-0.3)
INCLUDE_PATH = -I.
DEFNS := -D_REENTRANT -D_GNU_SOURCE
DEFNS += -DPWASIO_VERSION_MAJOR=$(VERSION_MAJOR)
DEFNS += -DPWASIO_VERSION_MINOR=$(VERSION_MINOR)
DEFNS += -DPWASIO_VERSION_PATCH=$(VERSION_PATCH)
DEFNS += -D__PROTON_7_BUILD__

ifeq ($(DEBUG),true)
CEXTRA += -O0 -g
DEFNS += -DDEBUG
else
CEXTRA += -O3 
DEFNS += -DNDEBUG
endif

ifneq ($(WINEBUILD_INCLUDEDIR),)
INCLUDE_PATH         += -I$(WINEBUILD_INCLUDEDIR)
else
INCLUDE_PATH         += \
                        -I$(PREFIX)/include/wine \
                        -I$(PREFIX)/include/wine/windows \
                        -I$(PREFIX)/include/wine-development \
                        -I$(PREFIX)/include/wine-development/wine/windows \
                        -I/opt/wine-stable/include \
                        -I/opt/wine-stable/include/wine/windows \
                        -I/opt/wine-staging/include \
                        -I/opt/wine-staging/include/wine/windows \
                        $(WINEBUILD_EXTRA_INCLUDEDIR)
endif

pwasio_dll_C_SRCS     = main.c \
		        pwasio.c
pwasio_dll_LDFLAGS  = -shared \
                      -m$(M) \
		      src/pwasio.dll.spec \
                      $(shell $(PKG_CONFIG) --libs libpipewire-0.3)

ifneq ($(WINEBUILD_LIBDIR),)
pwasio_dll_LDFLAGS += -L$(WINEBUILD_LIBDIR)
else
pwasio_dll_LDFLAGS += \
                        -L/usr/lib$(M)/wine \
                        -L/usr/lib/wine \
                        -L/usr/lib/$(ARCH)-linux-gnu/wine \
                        -L/usr/lib/$(ARCH)-linux-gnu/wine-development \
                        -L/opt/wine-stable/lib \
                        -L/opt/wine-stable/lib/wine \
                        -L/opt/wine-stable/lib$(M) \
                        -L/opt/wine-stable/lib$(M)/wine \
                        -L/opt/wine-staging/lib \
                        -L/opt/wine-staging/lib/wine \
                        -L/opt/wine-staging/lib$(M) \
                        -L/opt/wine-staging/lib$(M)/wine \
                        $(WINEBUILD_EXTRA_LIBDIR)
endif

pwasio_dll_OBJS     = $(pwasio_dll_C_SRCS:%.c=build$(M)/%.c.o)

### Generic targets

all:
build: $(DLLS:%=build$(M)/%)

### Build rules

.PHONY: all

### Implicit rules

build$(M)/%.c.o: src/%.c
	@$(shell mkdir -p build$(M))
	$(CC) -c $(DEFNS) $(INCLUDE_PATH) $(CEXTRA) -o $@ $<

### Target specific build rules

build$(M)/$(pwasio_dll_MODULE): $(pwasio_dll_OBJS)
	$(WINEBUILD) -m$(M) --dll --fake-module -E src/pwasio.dll.spec $^ -o $@

build$(M)/$(pwasio_dll_MODULE).so: $(pwasio_dll_OBJS)
	$(WINECC) $^ $(pwasio_dll_LDFLAGS) \
		-lodbc32 -lole32 -luuid -lwinmm -lshlwapi -o $@
